version: '3.2'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/src/
      - /usr/src/node_modules/
    container_name: clear-frontend-test
    ports:
      - 4005:4005